name: ci 
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install
        run: pip3 install mkdocs-material mkdocs-mermaid2-plugin
      - name: Build
        run: python3 -m mkdocs build
      - name: Publish
        if: ${{ github.event_name == 'push'}}
        run: python3 -m mkdocs gh-deploy --force
